apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-server
  namespace: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: info-server
  template:
    metadata:
      labels:
        app: info-server
    spec:
      containers:
      - name: info-server
        image: matst80/info-server:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: info-server
  namespace: home
spec:
  selector:
    app: info-server
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: info-server
  namespace: home
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
spec:
  tls:
  - hosts:
    - info.k6n.net
    secretName: info-k6n-net-tls
  rules:
  - host: info.k6n.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: info-server
            port:
              number: 8080