apiVersion: apps/v1
kind: Deployment
metadata:
  name: unms
  namespace: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unms
  template:
    metadata:
      labels:
        app: unms
    spec:
      containers:
      - name: unms
        image: nico640/docker-unms:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 2055
          protocol: UDP
        env:
        - name: TZ
          value: "Europe/Stockholm"  # Adjust as needed
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: unms-config-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unms-config-pvc
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: unms
  namespace: home
spec:
  selector:
    app: unms
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  - name: netflow
    port: 2055
    targetPort: 2055
    protocol: UDP
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unms
  namespace: home
  annotations:
    cert-manager.io/cluster-issuer: nginx1-clusterissuer
spec:
  tls:
  - hosts:
    - uisp.slask.local
    secretName: uisp-slask-local-tls
  rules:
  - host: uisp.slask.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: unms
            port:
              number: 80